'use strict';

module.exports = {
  up: async (queryInterface) => {
    return queryInterface.bulkInsert('beers', [
      {
        id: 'ef74b596-9db1-413e-be06-703c0c379cb5',
        name: 'Weihenstephaner Hefe-Weiss',
        minimum_temperature: -1,
        maximum_temperature: 3,
        average_temperature: 1,
        style: 'Weissbier',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: '4cf3c4e0-3552-44af-9991-8a43ca449ebc',
        name: 'Eisenbahn Pilsen',
        minimum_temperature: -2,
        maximum_temperature: 4,
        average_temperature: 1,
        style: 'Pilsens',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: '0e925143-fca6-40dd-8828-92b16b4a52f7',
        name: 'Eisenbahn Weizenbier',
        minimum_temperature: -4,
        maximum_temperature: 6,
        average_temperature: 1,
        style: 'Weizenbier',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 'b8788f21-b2cb-4ac7-b115-1bfd121a5e73',
        name: 'Irmãos Ferraro Pier',
        minimum_temperature: -5,
        maximum_temperature: 5,
        average_temperature: 0,
        style: 'Red ale',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: '6a48a2e7-4b53-403e-8a5a-0fdd387b84ce',
        name: 'India Pale Ale',
        minimum_temperature: -6,
        maximum_temperature: 7,
        average_temperature: 0.5,
        style: 'India pale ale',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: '144c7cab-833f-4a63-a4c2-8ed0be42b4f8',
        name: 'IPARTY',
        minimum_temperature: -7,
        maximum_temperature: 10,
        average_temperature: 1.5,
        style: 'IPA',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: '53f01e89-664c-4c70-aab0-fd890111bd9c',
        name: 'Dunkel',
        minimum_temperature: -8,
        maximum_temperature: 2,
        average_temperature: -3,
        style: 'Dunkel',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 'a29129ce-4158-4299-8e2f-863431b2de8c',
        name: 'Imperial Stouts',
        minimum_temperature: -10,
        maximum_temperature: 13,
        average_temperature: 1.5,
        style: 'Imperial Stouts',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 'cdb6d73a-01be-410c-83f5-b9bcb9c5bda0',
        name: 'Brown Ale',
        minimum_temperature: 0,
        maximum_temperature: 14,
        average_temperature: 7,
        style: 'Brown ale',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },
  down: async (queryInterface) => {
    return queryInterface.bulkDelete('beers', null, {});
  },
};
